env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - react
rules: { import/prefer-default-export: 'off', max-len: [100, 'error'], operator-linebreak: 'off' }
