env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - react
rules:
  {
    import/prefer-default-export: 'off',
    max-len: ['error', { code: 100, tabWidth: 2, ignoreUrls: true }],
    operator-linebreak: 'off',
    import/extensions: 'off',
    implicit-arrow-linebreak: 'off',
    '@typescript-eslint/indent': 'off',
    no-restricted-exports: 'off',
  }
